# Site
repository: srinuvallabhaneni/Static-Resume
# favicon: images/favicon.ico

# Personal info
name: Srinivas Vallabhaneni
title: Computer Science Master's Student
email: svallab4@asu.edu
website: www.github.com/srinuvallabhaneni/Static-Resume

# Social links
github_username:  srinuvallabhaneni
linkedin_username: srinivas-vallabhaneni
facebook_username: srinu.candy

# About Section
# about_title: About Me
about_profile_image: https://raw.githubusercontent.com/srinuvallabhaneni/Static-Resume/master/images/srinu1.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a Computer Science Master’s student specializing in Big Data Systems, currently working in Machine learning and AWS platform. 
  Actively looking for internship opportunities for summer 2019 to utilize my exemplary skills and gain experience.

  I am most skilled in: <mark>AWS</mark> , <mark>Data Analytics</mark> , <mark>Data Visualizations</mark> and <mark>Bio-Informatics tools</mark>

# Projects Section
# projects_title: Projects
projects_content: |
    
# Experience Section
# experience_title: Experience
experience_content: |
    

# Education Section
# educaton_title: Education
education_content: |
    
# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
