# Site
repository: srinuvallabhaneni/Static-Resume
# favicon: images/favicon.ico

# Personal info
name: Srinivas Vallabhaneni
title: Computer Science Master's Student
email: svallab4@asu.edu
website: www.github.com/srinuvallabhaneni/Static-Resume

# Social links
#twitter_username: facespics
github_username:  srinuvallabhaneni
# dribbble_username: jekyll
facebook_username: srinu.candy
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: srinivas-vallabhaneni
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/DSC_0163.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a Computer Science Master’s student specializing in Big Data Systems, currently working in Machine learning and AWS platform. 
  Actively looking for internship opportunities for summer 2019 to utilize my exemplary skills and gain experience.

  I am most skilled in: <mark>AWS</mark> <mark>Data Analytics</mark> , <mark>Data Visualizations</mark> and <mark>Bio-Informatics tools</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
